version: "3.8"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./backend:/app
    command: sh -c "./server & ./webserver"
    
  frontend:
    build:
      context: ./question-search-app
    ports:
      - "3000:3000"
    volumes:
      - ./question-search-app:/app
    command: npm start
