/**
 * @fileoverview gRPC-Web generated client stub for questionservice
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.20.3
// source: question.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as question_pb from './question_pb'; // proto import: "question.proto"


export class QuestionServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSearchQuestions = new grpcWeb.MethodDescriptor(
    '/questionservice.QuestionService/SearchQuestions',
    grpcWeb.MethodType.UNARY,
    question_pb.SearchRequest,
    question_pb.SearchResponse,
    (request: question_pb.SearchRequest) => {
      return request.serializeBinary();
    },
    question_pb.SearchResponse.deserializeBinary
  );

  searchQuestions(
    request: question_pb.SearchRequest,
    metadata?: grpcWeb.Metadata | null): Promise<question_pb.SearchResponse>;

  searchQuestions(
    request: question_pb.SearchRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: question_pb.SearchResponse) => void): grpcWeb.ClientReadableStream<question_pb.SearchResponse>;

  searchQuestions(
    request: question_pb.SearchRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: question_pb.SearchResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/questionservice.QuestionService/SearchQuestions',
        request,
        metadata || {},
        this.methodDescriptorSearchQuestions,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/questionservice.QuestionService/SearchQuestions',
    request,
    metadata || {},
    this.methodDescriptorSearchQuestions);
  }

}

